audit_header: false
title: Chicagoland's Best Real Estate Training
description: Gary Jacklin, a top Real Estate Agent in Chicagoland, shares his/her own internal real estate agent training for free. His/Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Presentation
    url: https://docs.google.com/presentation/d/1CasyxGtcCjygCfRPzEB3xrqq5ceIFvMd6Of6fria4LM/present?slide=id.p

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Why Work With RE/MAX?"
    CTA_text: "RE/MAX is the Market Leader in Chicagoland"
    CTA_link_text: "Learn More"
    CTA_url: https://docs.google.com/presentation/d/1CasyxGtcCjygCfRPzEB3xrqq5ceIFvMd6Of6fria4LM/present?slide=id.p

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/005.jpg
#     CTA_title2: "Looking for a Chicagoland Home?"
#     CTA_text2: "Search the entire MLS for your Chicagoland home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: /homesearch/

client:
  name: Gary Jacklin
  title:
  license_number:
  about_markdown: |
    Gary Jacklin has worked in real estate for 30 years in the Chicago suburbs, and he continues to innovate. As managing broker/owner of RE/ MAX Action, he’s been ranked No. 1 for internet marketing by RE/MAX Northern Illinois every year since 2003. Although Jacklin no longer lists and sells, he has been a top producer himself and understands what makes a successful top producer, and how agents can use technology to help them reach their goals. “Our RE/MAX Action agents continually compliment our staff, and the implementation of the leading-edge technology we provide and implement for them to help them service and grow their business,” he says.
  market: Chicagoland
  brand: RE/MAX Action
  brokerage:
  address: 1550 Maple Ave<br>Lisle, IL 60532
  phone: 630-968-2059
  phone_type:
  phone2:
  phone2_type:
  email: garyj@rma-mail.com
  url: http://www.joinrma.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/GaryJacklinREMAX/
  linkedin_url: https://www.linkedin.com/in/garyjacklinremax/
  gplus_url:
  youtube_url: https://www.youtube.com/user/garyjacklin1
  twitter_url: https://twitter.com/JoinRMA
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Chicagoland Real Estate Podcast with Gary Jacklin'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Chicagoland Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from RE/MAX Action - your professional Chicagoland Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Chicagoland, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Gary Jacklin'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Chicagoland Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#dd1c2f'
  theme_color: '#003ea5'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
